on:
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: Build Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
      - name: Compile Crates (Debug)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace
